YOU_ARE_NOT_A_CR='Only CR can add/update the links !'
SECTION_NOT_ASSIGNED='Oops your section is not assigned yet !'
SUBSECTION_NOT_ASSIGNED='Oops your subsection is not assigned yet !'
LINK_UPDATED='Thanks, for updating the meet link :) '
LINK_ADDED='Thanks, for adding the meet link '
NOT_A_VALID_COURSE='Oops there is no such course,please use a correct abbreviation'
NO_LINKS_AVAILABLE='Ask CR to add link for the course'